### ISSUE TITLE
Issues with Python 3.8

### ISSUE THREAD

**Issue by danielseipt** [fbpic/fbpic#517] opened 2021-03-01 17:01 UTC
Hi, 
I have recently observed some issues when running FBPIC (0.19.1) under Python 3.8. The code runs **without any error messages or warnings but produces completely wrong results**. When running the standard LWFA example https://fbpic.github.io/_downloads/a6ae9198fac12d614644f1312bc9feb7/lwfa_script.py it looks like some high plasma density is initialized close to the axis and that causes the problems. Attached are plots of the density rho at timestep 250 and 1500. 
Left panels show the incorrect behaviour with python 3.8.
The right panels are from a control run under python 3.7 showing the expected correct results. Under python 3.7 the unphysical behaviour never seemed to occur in my tests.

![download](https://user-images.githubusercontent.com/39627867/109524254-93f3e700-7ab0-11eb-8532-e2e2b0481778.png)
![download-1](https://user-images.githubusercontent.com/39627867/109524295-9d7d4f00-7ab0-11eb-96f6-d23cd11d7f23.png)

The problem so far only occurred using python 3.8. Using py3.8, I tried downgrading numba to 0.48 but that did not help. The problem occurred when running on GPU or CPU.

```
(fbpic38r) $ python lwfa_script.py 

FBPIC (0.19.1)

MPI available: Yes
MPI processes used: 1
MPI Library Information: 
Open MPI v4.0.2, package: Open MPI , ident: 4.0.2, repo rev: v4.0.2, Oct 07, 2019
CUDA available: Yes
Compute architecture: GPU (CUDA)
CUDA GPUDirect (MPI) enabled: No
FBPIC selected a Tesla V100S-PCIE-32GB GPU with id 0
```

```
# packages in environment at /home/user/miniconda3/envs/fbpic38r:
#
# Name                    Version                   Build  Channel
_libgcc_mutex             0.1                        main  
blas                      1.0                         mkl  
ca-certificates           2021.1.19            h06a4308_0  
certifi                   2020.12.5        py38h06a4308_0  
cudatoolkit               11.0.221             h6bb024c_0  
cupy-cuda110              8.5.0                    pypi_0    pypi
fastrlock                 0.5                      pypi_0    pypi
fbpic                     0.19.1                   pypi_0    pypi
h5py                      2.10.0           py38hd6299e0_1  
hdf5                      1.10.6               hb1b8bf9_0  
intel-openmp              2020.2                      254  
ld_impl_linux-64          2.33.1               h53a641e_7  
libedit                   3.1.20191231         h14c3975_1  
libffi                    3.3                  he6710b0_2  
libgcc-ng                 9.1.0                hdf63c60_0  
libgfortran-ng            7.3.0                hdf63c60_0  
libllvm9                  9.0.1                h4a3c616_1  
libstdcxx-ng              9.1.0                hdf63c60_0  
llvmlite                  0.31.0           py38hd408876_0  
mkl                       2020.2                      256  
mkl-service               2.3.0            py38he904b0f_0  
mkl_fft                   1.3.0            py38h54f3939_0  
mkl_random                1.1.1            py38h0573a6f_0  
mpi                       1.0                     openmpi    conda-forge
mpi4py                    3.0.3            py38h2e4b629_2    conda-forge
ncurses                   6.2                  he6710b0_1  
numba                     0.48.0           py38h0573a6f_0  
numpy                     1.19.2           py38h54aff64_0  
numpy-base                1.19.2           py38hfa32c7d_0  
openmpi                   4.0.2                hb1b8bf9_1  
openssl                   1.1.1j               h27cfd23_0  
pip                       21.0.1           py38h06a4308_0  
python                    3.8.8                hdb3f193_4  
python-dateutil           2.8.1                    pypi_0    pypi
python_abi                3.8                      1_cp38    conda-forge
readline                  8.1                  h27cfd23_0  
scipy                     1.6.1            py38h91f5cce_0  
setuptools                52.0.0           py38h06a4308_0  
six                       1.15.0           py38h06a4308_0  
sqlite                    3.33.0               h62c20be_0  
tbb                       2020.3               hfd86e86_0  
tk                        8.6.10               hbc83047_0  
wheel                     0.36.2             pyhd3eb1b0_0  
xz                        5.2.5                h7b6447c_0  
zlib                      1.2.11               h7b6447c_3  

```

**Comment by RemiLehe** [comment] 2021-03-01 17:14
Thanks a lot for reporting this issue! We'll look into it.

**Comment by danielseipt** [comment] 2021-03-01 17:53
Here are some additional plots. The electric fields are initialized the same way in both cases, but at iteration 50 (in fact already at iteration 1) the field strength Ex has increased by a factor 10. 



![py3738_it0000](https://user-images.githubusercontent.com/39627867/109535162-83496e00-7abc-11eb-8015-09eb12dc2bab.png)

![py3738_it0050](https://user-images.githubusercontent.com/39627867/109535657-1a162a80-7abd-11eb-9ab8-a18eadece395.png)

![py3738_it0500](https://user-images.githubusercontent.com/39627867/109537433-2a2f0980-7abf-11eb-8995-92beceee3e0d.png)

![py3738_it1000](https://user-images.githubusercontent.com/39627867/109537479-361acb80-7abf-11eb-8ecc-2576397c4819.png)

![py3738_it1750](https://user-images.githubusercontent.com/39627867/109537526-40d56080-7abf-11eb-9069-bb89a66780b3.png)

**Comment by RemiLehe** [comment] 2021-03-01 18:18
Hm, strange: so far, I have not been able to reproduce the above issue, neither on CPU nor on GPU. (I get the regular plot from the right, even with Python 3.8.)

Here is my environment:
```
# packages in environment at /home/rlehe/miniconda3/envs/py38:
#
# Name                    Version                   Build  Channel
_libgcc_mutex             0.1                        main  
blas                      1.0                         mkl  
ca-certificates           2021.1.19            h06a4308_0  
certifi                   2020.12.5        py38h06a4308_0  
cudatoolkit               10.0.130                      0  
cupy-cuda100              8.5.0                    pypi_0    pypi
fastrlock                 0.5                      pypi_0    pypi
fbpic                     0.19.1                   pypi_0    pypi
h5py                      2.10.0           py38hd6299e0_1  
hdf5                      1.10.6               hb1b8bf9_0  
intel-openmp              2020.2                      254  
ld_impl_linux-64          2.33.1               h53a641e_7  
libedit                   3.1.20191231         h14c3975_1  
libffi                    3.3                  he6710b0_2  
libgcc-ng                 9.1.0                hdf63c60_0  
libgfortran-ng            7.3.0                hdf63c60_0  
libllvm10                 10.0.1               hbcb73fb_5  
libstdcxx-ng              9.1.0                hdf63c60_0  
llvmlite                  0.34.0           py38h269e1b5_4  
mkl                       2020.2                      256  
mkl-service               2.3.0            py38he904b0f_0  
mkl_fft                   1.3.0            py38h54f3939_0  
mkl_random                1.1.1            py38h0573a6f_0  
ncurses                   6.2                  he6710b0_1  
numba                     0.51.2           py38h0573a6f_1  
numpy                     1.19.2           py38h54aff64_0  
numpy-base                1.19.2           py38hfa32c7d_0  
openssl                   1.1.1j               h27cfd23_0  
pip                       21.0.1           py38h06a4308_0  
python                    3.8.8                hdb3f193_4  
python-dateutil           2.8.1                    pypi_0    pypi
readline                  8.1                  h27cfd23_0  
scipy                     1.6.1            py38h91f5cce_0  
setuptools                52.0.0           py38h06a4308_0  
six                       1.15.0           py38h06a4308_0  
sqlite                    3.33.0               h62c20be_0  
tbb                       2020.3               hfd86e86_0  
tk                        8.6.10               hbc83047_0  
wheel                     0.36.2             pyhd3eb1b0_0  
xz                        5.2.5                h7b6447c_0  
zlib                      1.2.11               h7b6447c_3 
```

@danielseipt Would you have the time to reinstall your Python 3.8 environment from scratch? Maybe one of the dependencies had a bug and was recently updated... (I just re-installed from scratch less than an hour ago.)

**Comment by danielseipt** [comment] 2021-03-01 21:42
@RemiLehe I just reinstalled the python38 environment. Same spurious behaviour.

```
$ diff remi.txt fbpic38.txt 
24a25,26
> mpi                       1.0                     openmpi    conda-forge
> mpi4py                    3.0.3            py38h2e4b629_2    conda-forge
28a31
> openmpi                   4.0.2                hb1b8bf9_1  
32a36
> python_abi                3.8                      1_cp38    conda-forge
42c46
```
Then I deinstalled mpi (exactly same environment as yours) and it is still the same behaviour.

**Comment by MKirchen** [comment] 2021-03-01 22:14
I also cannot reproduce the issue using a fresh py38 environment with anaconda. (Tested on CPU)

```
_libgcc_mutex             0.1                        main
blas                      1.0                         mkl
ca-certificates           2020.12.5            ha878542_0    conda-forge
certifi                   2020.12.5        py38h578d9bd_1    conda-forge
fbpic                     0.19.1                   pypi_0    pypi
h5py                      2.10.0           py38hd6299e0_1
hdf5                      1.10.6               hb1b8bf9_0
intel-openmp              2020.2                      254
ld_impl_linux-64          2.33.1               h53a641e_7
libedit                   3.1.20191231         h14c3975_1
libffi                    3.3                  he6710b0_2
libgcc-ng                 9.1.0                hdf63c60_0
libgfortran-ng            7.3.0                hdf63c60_0
libllvm10                 10.0.1               hbcb73fb_5
libstdcxx-ng              9.1.0                hdf63c60_0
llvmlite                  0.34.0           py38h269e1b5_4
mkl                       2020.2                      256
mkl-service               2.3.0            py38he904b0f_0
mkl_fft                   1.3.0            py38h54f3939_0
mkl_random                1.1.1            py38h0573a6f_0
mpi                       1.0                     openmpi    conda-forge
mpi4py                    3.0.3            py38h2e4b629_2    conda-forge
ncurses                   6.2                  he6710b0_1
numba                     0.51.2           py38h0573a6f_1
numpy                     1.19.2           py38h54aff64_0
numpy-base                1.19.2           py38hfa32c7d_0
openmpi                   4.0.2                hb1b8bf9_1
openssl                   1.1.1j               h27cfd23_0
pip                       21.0.1           py38h06a4308_0
python                    3.8.8                hdb3f193_4
python-dateutil           2.8.1                    pypi_0    pypi
python_abi                3.8                      1_cp38    conda-forge
readline                  8.1                  h27cfd23_0
scipy                     1.6.1            py38h91f5cce_0
setuptools                52.0.0           py38h06a4308_0
six                       1.15.0           py38h06a4308_0
sqlite                    3.33.0               h62c20be_0
tbb                       2020.3               hfd86e86_0
tk                        8.6.10               hbc83047_0
wheel                     0.36.2             pyhd3eb1b0_0
xz                        5.2.5                h7b6447c_0
zlib                      1.2.11               h7b6447c_3
```

**Comment by MKirchen** [comment] 2021-03-01 22:21
@danielseipt Does the error look exactly the same on GPU and CPU?

**Comment by RemiLehe** [comment] 2021-03-01 22:37
@danielseipt Just a random thought: maybe the difference in observed behavior (even though we have the same environment) is due to some caching effect... Could you try the following:
```
rm -rf $HOME/.cupy/kernel_cache/     # Removes the GPU kernel that were previously compiled and cached
export FBPIC_DISABLE_CACHING=1   # Only controls the behavior on CPU, but who knows?
python lwfa_script.py
```

**Comment by danielseipt** [comment] 2021-03-01 23:33
@MKirchen  It is the same on GPU and GPU
@RemiLehe That didn't do anything

The CPU on that machine is AMD EPYC. Could this be relevant? But why should it affect the GPU result?

**Comment by RemiLehe** [comment] 2021-03-02 00:00
@danielseipt Interesting. In fact, even when you run on GPU, a few, selected operations are still done on CPU. In particular, the plasma initialization/injection (at the right-hand side of the simulation box) is still done on the CPU: 
https://github.com/fbpic/fbpic/blob/dev/fbpic/particles/injection/continuous_injection.py#L158
In principle, these are only `numpy` operations, so it would be strange that it produces a bug, but again: who knows.

That being said, I see that you have a number of packages that are Intel-specific in your environment (e.g. `intel-openmp` and `mkl`). Maybe these packages are buggy on AMD Epyc (and then they could maybe in turn [affect `numpy`](https://docs.anaconda.com/mkl-optimizations/index.html)). Note that, in this case, you will have to install `pyfftw` (`conda install -c conda-forge pyfftw`, as mentioned [here](https://fbpic.github.io/install/install_local.html))

**Comment by MKirchen** [comment] 2021-03-02 08:22
Using the same environment that I posted above, I could not reproduce the issue on an AMD EPYC node on my side.

**Comment by danielseipt** [comment] 2021-03-02 15:58
@RemiLehe You might have a point here. Without the `mkl` library, using `openblas` and `pyfftw` the problem is fixed on CPU. But not on GPU. I deleted the cupy cache as you suggested above (it was in fact downloaded again), and installed the cudatoolkit and fastrlock with --force-reinstall.

Do you want to investigate this further?

Maybe the simple solution is **Don't use Python 3.8 on EPYC CPUs, use Python 3.7**

```
#
# Name                    Version                   Build  Channel
_libgcc_mutex             0.1                        main  
blas                      1.0                    openblas  
ca-certificates           2021.1.19            h06a4308_0  
certifi                   2020.12.5        py38h06a4308_0  
cudatoolkit               11.0.221             h6bb024c_0  
cupy-cuda110              8.5.0                    pypi_0    pypi
fastrlock                 0.5              py38he6710b0_0  
fbpic                     0.19.1                   pypi_0    pypi
fftw                      3.3.9                h27cfd23_1  
h5py                      2.10.0           py38hd6299e0_1  
hdf5                      1.10.6               hb1b8bf9_0  
ld_impl_linux-64          2.33.1               h53a641e_7  
libedit                   3.1.20191231         h14c3975_1  
libffi                    3.3                  he6710b0_2  
libgcc-ng                 9.1.0                hdf63c60_0  
libgfortran-ng            7.3.0                hdf63c60_0  
libllvm10                 10.0.1               hbcb73fb_5  
libopenblas               0.3.10               h5a2b251_0  
libstdcxx-ng              9.1.0                hdf63c60_0  
llvmlite                  0.34.0           py38h269e1b5_4  
ncurses                   6.2                  he6710b0_1  
nomkl                     3.0                           0  
numba                     0.51.2           py38h0573a6f_1  
numpy                     1.19.2           py38h6163131_0  
numpy-base                1.19.2           py38h75fe3a5_0  
openblas                  0.3.10                        0  
openblas-devel            0.3.10                        0  
openssl                   1.1.1j               h27cfd23_0  
pip                       21.0.1           py38h06a4308_0  
pyfftw                    0.12.0           py38h9004437_2    conda-forge
python                    3.8.8                hdb3f193_4  
python-dateutil           2.8.1                    pypi_0    pypi
python_abi                3.8                      1_cp38    conda-forge
readline                  8.1                  h27cfd23_0  
scipy                     1.6.1            py38hf56f3a7_0  
setuptools                52.0.0           py38h06a4308_0  
six                       1.15.0           py38h06a4308_0  
sqlite                    3.33.0               h62c20be_0  
tbb                       2020.3               hfd86e86_0  
tk                        8.6.10               hbc83047_0  
wheel                     0.36.2             pyhd3eb1b0_0  
xz                        5.2.5                h7b6447c_0  
zlib                      1.2.11               h7b6447c_3  
```

**Comment by MKirchen** [comment] 2021-03-02 17:45
We are still trying to get some insight where the issue comes from.

@danielseipt Could you specify the exact AMD Epyc model that you use?

Also, do you have the chance to test your installation on an Intel machine for direct comparison?

Thanks!

**Comment by danielseipt** [comment] 2021-03-02 19:46
Here's the CPU:

```
$ cat /proc/cpuinfo 
processor	: 0
vendor_id	: AuthenticAMD
cpu family	: 23
model		: 49
model name	: AMD EPYC 7702 64-Core Processor
stepping	: 0
microcode	: 0x8301034
cpu MHz		: 3301.721
cache size	: 512 KB
physical id	: 0
siblings	: 128
core id		: 0
cpu cores	: 64
apicid		: 0
initial apicid	: 0
fpu		: yes
fpu_exception	: yes
cpuid level	: 16
wp		: yes
flags		: fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush mmx fxsr sse sse2 ht syscall nx mmxext fxsr_opt pdpe1gb rdtscp lm constant_tsc rep_good nopl nonstop_tsc cpuid extd_apicid aperfmperf pni pclmulqdq monitor ssse3 fma cx16 sse4_1 sse4_2 x2apic movbe popcnt aes xsave avx f16c rdrand lahf_lm cmp_legacy svm extapic cr8_legacy abm sse4a misalignsse 3dnowprefetch osvw ibs skinit wdt tce topoext perfctr_core perfctr_nb bpext perfctr_llc mwaitx cpb cat_l3 cdp_l3 hw_pstate sme ssbd mba sev ibrs ibpb stibp vmmcall fsgsbase bmi1 avx2 smep bmi2 cqm rdt_a rdseed adx smap clflushopt clwb sha_ni xsaveopt xsavec xgetbv1 xsaves cqm_llc cqm_occup_llc cqm_mbm_total cqm_mbm_local clzero irperf xsaveerptr wbnoinvd arat npt lbrv svm_lock nrip_save tsc_scale vmcb_clean flushbyasid decodeassists pausefilter pfthreshold avic v_vmsave_vmload vgif umip rdpid overflow_recov succor smca
bugs		: sysret_ss_attrs spectre_v1 spectre_v2 spec_store_bypass
bogomips	: 3992.39
TLB size	: 3072 4K pages
clflush size	: 64
cache_alignment	: 64
address sizes	: 43 bits physical, 48 bits virtual
power management: ts ttp tm hwpstate cpb eff_freq_ro [13] [14]
```



I did run fbpic with the same python 3.8 environment (only python-dateutil is different) on an Intel(R) Xeon(R) CPU E5-2683 v4 @ 2.10GHz. Results look correct.

```
#
# Name                    Version                   Build  Channel
_libgcc_mutex             0.1                        main  
blas                      1.0                         mkl  
ca-certificates           2021.1.19            h06a4308_0  
certifi                   2020.12.5        py38h06a4308_0  
cudatoolkit               10.0.130                      0  
cupy-cuda100              8.5.0                    pypi_0    pypi
fastrlock                 0.5                      pypi_0    pypi
fbpic                     0.19.1                   pypi_0    pypi
h5py                      2.10.0           py38hd6299e0_1  
hdf5                      1.10.6               hb1b8bf9_0  
intel-openmp              2020.2                      254  
ld_impl_linux-64          2.33.1               h53a641e_7  
libedit                   3.1.20191231         h14c3975_1  
libffi                    3.3                  he6710b0_2  
libgcc-ng                 9.1.0                hdf63c60_0  
libgfortran-ng            7.3.0                hdf63c60_0  
libllvm10                 10.0.1               hbcb73fb_5  
libstdcxx-ng              9.1.0                hdf63c60_0  
llvmlite                  0.34.0           py38h269e1b5_4  
mkl                       2020.2                      256  
mkl-service               2.3.0            py38he904b0f_0  
mkl_fft                   1.3.0            py38h54f3939_0  
mkl_random                1.1.1            py38h0573a6f_0  
ncurses                   6.2                  he6710b0_1  
numba                     0.51.2           py38h0573a6f_1  
numpy                     1.19.2           py38h54aff64_0  
numpy-base                1.19.2           py38hfa32c7d_0  
openssl                   1.1.1j               h27cfd23_0  
pip                       21.0.1           py38h06a4308_0  
python                    3.8.8                hdb3f193_4  
python-dateutil           2.8.1              pyhd3eb1b0_0  
readline                  8.1                  h27cfd23_0  
scipy                     1.6.1            py38h91f5cce_0  
setuptools                52.0.0           py38h06a4308_0  
six                       1.15.0           py38h06a4308_0  
sqlite                    3.33.0               h62c20be_0  
tbb                       2020.3               hfd86e86_0  
tk                        8.6.10               hbc83047_0  
wheel                     0.36.2             pyhd3eb1b0_0  
xz                        5.2.5                h7b6447c_0  
zlib                      1.2.11               h7b6447c_3  

```

**Comment by RemiLehe** [comment] 2021-03-04 20:03
Thanks again for reporting this issue @danielseipt!
For now, it seems that this might be a somewhat isolated issue - or at least it is unclear how to reproduce it, including on the AMD Epyc hardware that we have access to on our side.
If more users report the same issue, we'll take another look and try to modify the code to raise a warning.

**Comment by MKirchen** [comment] 2021-09-17 13:56
I will close this issue for now. We can reopen it in case more users report this problem.

**Closed by MKirchen** 2021-09-17 13:56 UTC
Labels: bug
