### ISSUE TITLE
running with MPI 

### ISSUE THREAD

**Issue by rezaplasma** [fbpic/fbpic#648] opened 2023-06-21 16:09 UTC
Hi
I have installed fbpic and that's dependencies with `conda ` on clustered system
when I run script with `mpirun -n 4 python fbpic_script.py ` , the below error occurres

```
UserWarning: /home/ubuntu/anaconda3/lib/python3.10/site-packages/fbpic/utils/mpi.py:47:
MPI is not properly installed.
Simulations without domain decomposition will still run properly.
In order to diagnose the problem, type:
mpirun -np 2 python -c "from mpi4py.MPI import COMM_WORLD"

UserWarning: /home/ubuntu/anaconda3/lib/python3.10/site-packages/fbpic/utils/mpi.py:47:
MPI is not properly installed.
Simulations without domain decomposition will still run properly.
In order to diagnose the problem, type:
mpirun -np 2 python -c "from mpi4py.MPI import COMM_WORLD"

UserWarning: /home/ubuntu/anaconda3/lib/python3.10/site-packages/fbpic/utils/mpi.py:47:
MPI is not properly installed.
Simulations without domain decomposition will still run properly.
In order to diagnose the problem, type:
mpirun -np 2 python -c "from mpi4py.MPI import COMM_WORLD"

UserWarning: /home/ubuntu/anaconda3/lib/python3.10/site-packages/fbpic/utils/mpi.py:47:
MPI is not properly installed.
Simulations without domain decomposition will still run properly.
In order to diagnose the problem, type:
mpirun -np 2 python -c "from mpi4py.MPI import COMM_WORLD"

FBPIC (0.24.0)

Running on CPU (8 threads per process)

Initializing laser pulse on the mesh...

FBPIC (0.24.0)

Running on CPU (8 threads per process)

Initializing laser pulse on the mesh...

FBPIC (0.24.0)

Running on CPU (8 threads per process)

Initializing laser pulse on the mesh...

FBPIC (0.24.0)

Running on CPU (8 threads per process)

Initializing laser pulse on the mesh...
Done.

Just-In-Time compilation (up to one minute) ...Done.

Just-In-Time compilation (up to one minute) ...Done.

Just-In-Time compilation (up to one minute) ...Done.

|                                   | 51/1800, 0:03:42 left, 119 ms/stepTraceback (most recent call last):
  File "/home/ubuntu/lwfa_script.py", line 152, in <module>
    sim.step( N_step )
  File "/home/ubuntu/anaconda3/lib/python3.10/site-packages/fbpic/main.py", line 482, in step
    diag.write( self.iteration )
  File "/home/ubuntu/anaconda3/lib/python3.10/site-packages/fbpic/openpmd_diag/generic_diag.py", line 140, in write
    self.write_hdf5( iteration )
  File "/home/ubuntu/anaconda3/lib/python3.10/site-packages/fbpic/openpmd_diag/field_diag.py", line 122, in write_hdf5
    self.create_file_empty_meshes(
  File "/home/ubuntu/anaconda3/lib/python3.10/site-packages/fbpic/openpmd_diag/field_diag.py", line 259, in create_file_empty_meshes
    f = self.open_file( fullpath )
  File "/home/ubuntu/anaconda3/lib/python3.10/site-packages/fbpic/openpmd_diag/generic_diag.py", line 117, in open_file
    f = h5py.File( fullpath, mode="a" )
  File "/home/ubuntu/anaconda3/lib/python3.10/site-packages/h5py/_hl/files.py", line 533, in __init__
    fid = make_fid(name, mode, userblock_size, fapl, fcpl, swmr=swmr)
  File "/home/ubuntu/anaconda3/lib/python3.10/site-packages/h5py/_hl/files.py", line 238, in make_fid
    fid = h5f.open(name, h5f.ACC_RDWR, fapl=fapl)
  File "h5py/_objects.pyx", line 54, in h5py._objects.with_phil.wrapper
  File "h5py/_objects.pyx", line 55, in h5py._objects.with_phil.wrapper
  File "h5py/h5f.pyx", line 106, in h5py.h5f.open
BlockingIOError: [Errno 11] Unable to open file (unable to lock file, errno = 11, error message = 'Resource temporarily unavailable')
|                                   | 51/1800, 0:03:42 left, 119 ms/stepTraceback (most recent call last):
  File "/home/ubuntu/lwfa_script.py", line 152, in <module>
    sim.step( N_step )
  File "/home/ubuntu/anaconda3/lib/python3.10/site-packages/fbpic/main.py", line 482, in step
    diag.write( self.iteration )
  File "/home/ubuntu/anaconda3/lib/python3.10/site-packages/fbpic/openpmd_diag/generic_diag.py", line 140, in write
    self.write_hdf5( iteration )
  File "/home/ubuntu/anaconda3/lib/python3.10/site-packages/fbpic/openpmd_diag/field_diag.py", line 122, in write_hdf5
    self.create_file_empty_meshes(
  File "/home/ubuntu/anaconda3/lib/python3.10/site-packages/fbpic/openpmd_diag/field_diag.py", line 259, in create_file_empty_meshes
    f = self.open_file( fullpath )
  File "/home/ubuntu/anaconda3/lib/python3.10/site-packages/fbpic/openpmd_diag/generic_diag.py", line 117, in open_file
    f = h5py.File( fullpath, mode="a" )
  File "/home/ubuntu/anaconda3/lib/python3.10/site-packages/h5py/_hl/files.py", line 533, in __init__
    fid = make_fid(name, mode, userblock_size, fapl, fcpl, swmr=swmr)
  File "/home/ubuntu/anaconda3/lib/python3.10/site-packages/h5py/_hl/files.py", line 238, in make_fid
    fid = h5f.open(name, h5f.ACC_RDWR, fapl=fapl)
  File "h5py/_objects.pyx", line 54, in h5py._objects.with_phil.wrapper
  File "h5py/_objects.pyx", line 55, in h5py._objects.with_phil.wrapper
  File "h5py/h5f.pyx", line 106, in h5py.h5f.open
BlockingIOError: [Errno 11] Unable to open file (unable to lock file, errno = 11, error message = 'Resource temporarily unavailable')
-------------------------------------------------------
Primary job  terminated normally, but 1 process returned
a non-zero exit code.. Per user-direction, the job has been aborted.
-------------------------------------------------------
|-                                  | 54/1800, 0:03:35 left, 106 ms/step--------------------------------------------------------------------------
mpirun detected that one or more processes exited with non-zero status, thus causing
the job to be terminated. The first process to do so was:

  Process name: [[49659,1],1]
  Exit code:    1
```

although I have already installed and run script with `mpi` on this system without getting any errors
should be mentioned the all dependencies are also installed

how can I improve this issue?

thanks.

**Comment by RemiLehe** [comment] 2023-06-21 16:11
Hi @rezaplasma 
Did you try to run 
```
mpirun -np 2 python -c "from mpi4py.MPI import COMM_WORLD"
```
as suggested by the above messages?
If yes, do you get an error message when running the above command?

**Comment by rezaplasma** [comment] 2023-06-21 16:21
hi @RemiLehe 

thanks for your answer
yes, I tried and again got below error

```
(base) ubuntu@ubuntu-virtual-machine:~$ mpirun -np 2 python -c "from mpi4py.MPI import COMM_WORLD"
Traceback (most recent call last):
  File "<string>", line 1, in <module>
ImportError: libmpi.so.12: cannot open shared object file: No such file or directory
Traceback (most recent call last):
  File "<string>", line 1, in <module>
ImportError: libmpi.so.12: cannot open shared object file: No such file or directory
-------------------------------------------------------
Primary job  terminated normally, but 1 process returned
a non-zero exit code.. Per user-direction, the job has been aborted.
-------------------------------------------------------
--------------------------------------------------------------------------
mpirun detected that one or more processes exited with non-zero status, thus causing
the job to be terminated. The first process to do so was:

  Process name: [[50412,1],0]
  Exit code:    1
--------------------------------------------------------------------------
```

**Comment by RemiLehe** [comment] 2023-06-21 19:43
OK, thanks. 
The above test shows that your MPI installation has a problem. (Note that the test `mpirun -np 2 python -c "from mpi4py.MPI import COMM_WORLD"` does not involve FBPIC: this is purely an MPI issue.)
I would recommend trying to reinstall MPI. If the problem persist, please contact MPI developers.

Since the problem is not specific to FBPIC, I will close this issue for now.

**Closed as completed** 2023-06-21 19:43 UTC

**Comment by rezaplasma** [comment] 2023-06-28 21:37
Hi @RemiLehe

I installed the lower version of `conda` and `mpi` was installed separately then the problem was resolved.
I don't know if it has anything to do with the problem or not, but the problem is solved

Thanks
