### ISSUE TITLE
errors when using more nodes and cores

### ISSUE THREAD

**Issue by QJohn2017** [fbpic/fbpic#362] opened 2019-05-25 05:05 UTC
Hi, @MKirchen , 
1. When I set `n_order=32` and using `#!/bin/bash
export NUMBA_NUM_THREADS=12
export MKL_NUM_THREADS=12
yhrun -N 8 -n 16 python lwfa_script.py`  to run the FBPIC simulation, the some errors occurred in the attachment files
[8 nodes and 32 n_orders.txt](https://github.com/fbpic/fbpic/files/3219134/8.nodes.and.32.n_orders.txt)

2. Then, I set `n_order=128` and also using 8 nodes to run this simulation, the errors also appeared in the attachment files 
[8 nodes and 128 n_orders.txt](https://github.com/fbpic/fbpic/files/3219135/8.nodes.and.128.n_orders.txt)

3. But if I only use 4 nodes `#!/bin/bash
export NUMBA_NUM_THREADS=12
export MKL_NUM_THREADS=12
yhrun -N 4 -n 8 python lwfa_script.py`
and set  `n_order=32` , the simulation is good running and no errors appeared.

some of my input parameters are below:
![11](https://user-images.githubusercontent.com/31507149/58364875-8bd74280-7eed-11e9-941e-f003158f1c96.jpg)

I don't know what the problem is, looking forward to your reply, thank you !

**Comment by MKirchen** [comment] 2019-05-25 18:38
Hi,

this is not an error but just a limitation of how the code works. 

The box is split to many small boxes (one for each MPI process) in the longitudinal (z) direction and they have a boundary layer that is used to exchange the information betwen the neighbouring boxes. The size of those boundary layers (n_guard) is defined by the parameter n_order, which also defines the accuracy of the field solver. Larger order means larger boundary layers and also higher accuracy (typically order 32 is good enough). 

The error that you see is the following:

ValueError: Number of local cells in z is smaller than 4 times n_guard. Use fewer domains or a smaller number of guard cells.

The problem is that you used too many MPI processes or a too high order. In either cases each small box is too small compared to the size of the boundary layers (n_guard) for this order (n_order).

Please just use fewer MPI processes or choose a smaller order.

**Comment by QJohn2017** [comment] 2019-05-26 06:14
Okay, thank you for your answer! According to your suggestion, when i set `n_order=16` and use `N=8, n=16 ` MPI processes, the errors above disappeared and the simulation runs normally. But in this case, the accuracy decreased, so here another question is opened:
As you have noted above, the value of `n_order` defines the `n_guard`, and also defines the computational accuracy. A larger `n_order` value represents a large  `n_guard` (which has a relation : `n_guard=2*n_order`, is it right? ), meanwhile A larger `n_order` value also represents a higher computational accuracy. But If I want to use more MPI processes, there should be a lower  `n_order` value and a lower  `n_guard` value, but accordingly means a lower computational accuracy. So, my question is that, if I want to use more MPI processes (i.e., N=8 and n=16) to save computing time, but I also want to ensure the accuracy (i,e, ensure a higher `n_order` value), how should I do? Thank you !

**Comment by MKirchen** [comment] 2019-05-27 12:15
@QJohn2017,

Your understanding of the relation between `n_order` and `n_guard` is correct (However, please note that the scaling `n_guard = 2*n_order` is only approximately correct and the scaling is slightly non-linear in reality).

To answer your question:

When using a reasonable accuracy (such as `n_order=32`), the minimum physical size of a single MPI domain needs to be approximately `2*n_guard = 4*n_order = 128 cells`. If you use too many MPI processes, the physical domain size gets smaller than this value and the code will throw the error that you saw. However, if your domain size is already as small as 128 cells, a single MPI process will most likely not run faster by decreasing the domain size further. If you really want to have even smaller domain sizes, the algorithm of FBPIC requires you to choose a lower accuracy, i.e. a lower `n_order`.

I strongly advice you to not increase the number of MPI domains further for your simulation box size. I highly doubt that the runtime of your simulation will decrease even further by using more MPI processes as the domain sizes are already very small.

Rather than increasing the number of MPI processes, you should investigate (together with your administrators) how to increase the simulation speed using fewer MPI processes. In your previous issue, you reported that the speed of the simulation did only increase very slightly when going from 2 to 4 MPI processes. This could for example be related to a poor performance of the MPI communication on your supercomputer and your administrators can help you improving it.

Please also note that scaling to more MPI processes is typically only efficient if a single iteration takes more than one hundred ms. If your simulation already only takes ~100 ms per step, it is not efficient to use even more MPI processes.

**Comment by QJohn2017** [comment] 2019-05-27 12:43
@MKirchen , In my case, if I use 4 nodes and set `n_order=32`, the time in a single iteration is about ~1500ms，which is more than hundred ms。
But, when I use 8 nodes, and set `n_order=16`, the time in a single iteration is about ~850 ms, which is also more than hundred ms。
If 4 nodes are used, and `n_order=32`, by partial simulation, It can be predicted that it will take 3.5 days to fully simulate a case .
Now, I want to decrease the simulation time but maintain the computational accuracy (i.e., a higher `n_order`, e.g., 32), so, i wish to increase the MPI processes to achieve it, Is there nothing I can do?

**Comment by MKirchen** [comment] 2019-05-27 13:10
No, as I explained above, a certain order requires a minimum physical domain size.

Would you mind sharing the input script that you use for your simulation? I might take a look at it to estimate what speed can be expected.

**Comment by QJohn2017** [comment] 2019-05-27 13:25
the input file is attachment files, because it is not support to upload `.py` format file, so I transfer it to `.txt` format.
[lwfa_script.txt](https://github.com/fbpic/fbpic/files/3223908/lwfa_script.txt)

**Comment by QJohn2017** [comment] 2019-05-30 05:54
@MKirchen  @RemiLehe @soerenjalas , can you speed up the run time of my input script above ? Thank you !

**Comment by MKirchen** [comment] 2019-05-30 17:12
Hey @QJohn2017,

I have a few things for you to try out:

1) Please run `numba -s` on your machine and post the result here. This will help me understand what kind of CPU settings you are running on. Ideally, you execute this command on a compute node. So maybe you have to do something like `yhrun -N 1 -n 1 numba -s`.

2) I have slightly modified your script so that we can quickly do some benchmarking: 

Please download it here: 
[qjohn.txt](https://github.com/fbpic/fbpic/files/3237941/qjohn.txt)

I made sure that the entire box is filled with particles from the beginning by setting `p_zmin= -64.e-6`and `dens_func=None`. Also, the simulation will print additional information about how it is executed because I added the parameter `verbose_level=2` to the `Simulation()` object. Finally, the script will run 10 initial steps `sim.step(10)` were the initial compilation will happen. The performance is then measured by the following 200 steps `sim.step(200)`. The relevant number for the performance is the last line printed by the script: `Average time per iteration (with compilation): xxx ms`.

Please run this script using the following command:

`#!/bin/bash export NUMBA_NUM_THREADS=12 export MKL_NUM_THREADS=12 yhrun -N 2 -n 4 --cpu_bind=socket python qjohn.py` and post the results here. This should execute 4 MPI processes on 2 different nodes with 12 threads per MPI process.

Additionally, you can try two more things and see if it decreases the runtime:

a) additionally add `export OMP_NUM_THREADS=12` to the executing command.
b) replace `-n 4` by `--ntasks_per_node=2` in the executing command. (This explicitly tells to use 2 MPI processes per node, i.e. 4 MPI processes in total will be created as there are `-N 2` two nodes requested.

**Expected performance:**
For comparison here are some benchmark results on another supercomputer running the script:

```
1 nodes,12 threads,1 MPI processes: Average time per iteration (with compilation): 569 ms
1 nodes,12 threads,2 MPI processes: Average time per iteration (with compilation): 351 ms
2 nodes,12 threads,4 MPI processes: Average time per iteration (with compilation): 198 ms
4 nodes,12 threads,8 MPI processes: Average time per iteration (with compilation): 116 ms
```

As you can see, it should be possible to get ~100-200 ms average time per step for your simulation with 8 or less MPI processes.

**Comment by QJohn2017** [comment] 2019-05-31 11:24
Hi, @MKirchen , 
1. the results that by typing the command `numba -s` are 
[output.txt](https://github.com/fbpic/fbpic/files/3240873/output.txt)

2. By using the input script above, and using the script command `#!/bin/bash export NUMBA_NUM_THREADS=12 export MKL_NUM_THREADS=12 yhrun -N 2 -n 4 --cpu_bind=socket python qjohn.py`, the results are below:
`
2 nodes,12 threads,4 MPI processes (with --cpu_bind=socket option): Average time per iteration (with compilation): 2717 ms
nodes,12 threads,4 MPI processes (without --cpu_bind=socket option): Average time per iteration (with compilation): 2737 ms
4 nodes,12 threads,8 MPI processes (with --cpu_bind=socket option): Average time per iteration (with compilation): 1784 ms
2 nodes,12 threads,4 MPI processes (with --cpu_bind=socket option & export OMP_NUM_THREADS=12 option): Average time per iteration (with compilation): 2734 ms

`
Besides, 3. by using my original input file and using `4 nodes` , the Average time per iteration is `2193 ms`.
4. when I using  `--ntasks_per_node=2` option, errors occurred, so when I type the command `srun --help`, the results are below:
![11](https://user-images.githubusercontent.com/31507149/58702756-4200c780-83d9-11e9-9817-f8202429c9e7.jpg)

5. you have recommend that you have set  `dens_func=None`, what does this means? does it means there are no plasma density in the simulation zone?

**Comment by MKirchen** [comment] 2019-05-31 11:27
Sorry, can you try `--ntasks-per-node`

**Comment by MKirchen** [comment] 2019-05-31 11:34
Please also again run the benchmark script that I've sent you with only 1 node and 1 MPI process and post the average time per step. Please only use the script that I have sent you for performance tests so that there is no confusion. Please always use --cpu_bind=socket (it will not have a negative effect on performance, but can only have a positive one in this case).

**Comment by QJohn2017** [comment] 2019-05-31 11:40
when I use `--ntasks_per_node` option, it returns: `yhrun: error: --ntasks must be set with --exclusive
`

**Comment by MKirchen** [comment] 2019-05-31 11:46
It could be that the simulation is not running on dedicated nodes exclusively used for your simulation job. Please carefully read the documentation of your supercomputer or contact your administrators so that they can explain to you how to correctly submit jobs to multiple, dedicated compute nodes that are not shared.

Two more things to try:

1) Try to use the `--exclusive` option.
2) Please send me the complete output printed by the benchmark simulation script when you executed it with `#!/bin/bash export NUMBA_NUM_THREADS=12 export MKL_NUM_THREADS=12 yhrun -N 2 -n 4 --cpu_bind=socket python qjohn.py`

**Comment by QJohn2017** [comment] 2019-05-31 12:02
the complete output printed by the benchmark simulation script are 
[slurm-11443621.txt](https://github.com/fbpic/fbpic/files/3241159/slurm-11443621.txt)

I used the `--exclusive`, the errors above occurred again

**Comment by QJohn2017** [comment] 2019-05-31 12:15
when I use 1 node and 1 MPI process,that is `#!/bin/bash
export NUMBA_NUM_THREADS=12
export MKL_NUM_THREADS=12
export OMP_NUM_THREADS=12
yhrun -N 1 -n 1 --cpu_bind=sockets python qjohn.py
`

the `Average time per iteration (with compilation): 7599 ms`
and the output file is 
[slurm-11444398.txt](https://github.com/fbpic/fbpic/files/3241198/slurm-11444398.txt)

**Comment by MKirchen** [comment] 2019-05-31 12:25
Okay, as you can see, there is clearly a much worse performance of the compute nodes of your supercomputer compared to the one that I used. 7600ms in your case compared to 560ms in my example. It is impossible for me to diagnose why your compute units perform that bad - You need to ask your administrators for help.

One last thing to try: 

Maybe it helps to install Intel TBB by doing `conda install tbb` and then you additionally add `export NUMBA_THREADING_LAYER=tbb` to your execution command.

**Comment by QJohn2017** [comment] 2019-05-31 13:39
when I install the `tbb` and use `export NUMBA_THREADING_LAYER=tbb` option:
`#!/bin/bash
export NUMBA_NUM_THREADS=12
export MKL_NUM_THREADS=12
export NUMBA_THREADING_LAYER=tbb
yhrun -N 2 -n 4 --cpu_bind=sockets python qjohn.py
`
the `Average time per iteration (with compilation): 3154 ms` , and the output file is 
[slurm-11444973.txt](https://github.com/fbpic/fbpic/files/3241441/slurm-11444973.txt)

which can be seen that this performance is not good.

PS : why your supercomputing center time is just `560 ms`, do you used the GPU in simulation ?

**Comment by MKirchen** [comment] 2019-05-31 14:18
No, this was on CPU of course. 

Unfortunately, the conclusion for me is that the long runtime is related to your supercomputer‘s CPU performance. Please contact your administrators and ask for help.

The issue is not related to FBPIC and I will therefore close it now.

**Closed by MKirchen** 2019-05-31 14:18 UTC
