### ISSUE TITLE
Convergence of boosted frame and lab frame simulations (external injection emittance)

### ISSUE THREAD

**Issue by ycaophysics** [fbpic/fbpic#627] opened 2022-11-22 23:02 UTC
Hi. In one of my convergence tests, I tried both lab frame and boosted frame for about the same distance. The a0 and energy gain plots are pretty much the same. However, for externally injected beam emittance, there's a drastic increase of emittance at 6cm with FBPIC. How would you interpret that result? 
Here are the plots:
![image](https://user-images.githubusercontent.com/70364621/203435273-4ad2181b-92d1-4fce-8aa1-91ccd8329e12.png)

Here are the scripts. The parameters are not exactly the same for saving computation power. Also, the externally injected file are made with script below (so a little random difference doesn't cause big problem I guess):
[ConvergenceTest.zip](https://github.com/fbpic/fbpic/files/10071695/ConvergenceTest.zip)

**Comment by RemiLehe** [comment] 2022-11-29 17:24
Thanks a lot for reporting this issue!
This is indeed not expected. We'll try to have a closer look at this soon.

**Comment by MKirchen** [comment] 2024-03-09 11:59
Dear @ycaophysics, sorry for the late reply. It seems that the two scripts that you shared are significantly different, which could be the reason for the observed differences in the emittance. Please try to reproduce the issue using exactly the same simulation parameters for the lab and boosted frame simulation. I will close this issue for now. Feel free to reopen it if you are convinced that there is an issue with the code.

**Closed by MKirchen** 2024-03-09 11:59 UTC
