### ISSUE TITLE
output data for multinode run

### ISSUE THREAD

**Issue by Korsidar** [fbpic/fbpic#372] opened 2019-06-11 07:25 UTC
Hello, I build FBPic with Anaconda, and when I run code over 2 nodes I get only a half of information in output files. View it with OpenPMDviewer.

![Parallel_run_2_nodes](https://user-images.githubusercontent.com/47625176/59251480-16d96c00-8c54-11e9-8519-22f666dc100a.png) 

Cluster configuration: 1 node contains 2 processors with 18 cores. 

Run with:
```
#!/bin/bash 
#PBS -N ILP_FBPic_300
#PBS -l nodes=2:intel:ppn=36,pmem=3400mb,pvmem=200000mb,walltime=200:00:00
SUFFIX=$USER/${PBS_JOBNAME}_$(date +%F_%T)
WDIR=/store/$SUFFIX
GDIR=/store/nodes/$HOSTNAME/$SUFFIX
cd $PBS_O_WORKDIR
mkdir -p FBPic_300
cd FBPic_300
cp $PBS_O_WORKDIR/*py ./
cp $PBS_O_WORKDIR/*sh ./
export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:/lib64/:/share/apps/intel/composer_xe_2013_sp1.0.080/compiler/lib/intel64/
export OMP_NUM_THREADS=1
export NUMBA_NUM_THREADS=18
export MKL_NUM_THREADS=18
~/anaconda3/bin/mpirun -np 4 -ppn 2  --bind-to socket ~/anaconda3/bin/python3 lwfa_script.py 
```

Conda info:
```
     active environment : None
       user config file : /home/ptuev/.condarc
 populated config files : /home/ptuev/.condarc
          conda version : 4.6.14
    conda-build version : 3.17.8
         python version : 3.7.3.final.0
       base environment : /home/ptuev/anaconda3  (writable)
           channel URLs : https://conda.anaconda.org/conda-forge/linux-64
                          https://conda.anaconda.org/conda-forge/noarch
                          https://repo.anaconda.com/pkgs/main/linux-64
                          https://repo.anaconda.com/pkgs/main/noarch
                          https://repo.anaconda.com/pkgs/free/linux-64
                          https://repo.anaconda.com/pkgs/free/noarch
                          https://repo.anaconda.com/pkgs/r/linux-64
                          https://repo.anaconda.com/pkgs/r/noarch
          package cache : /home/ptuev/anaconda3/pkgs
                          /home/ptuev/.conda/pkgs
       envs directories : /home/ptuev/anaconda3/envs
                          /home/ptuev/.conda/envs
               platform : linux-64
             user-agent : conda/4.6.14 requests/2.21.0 CPython/3.7.3 Linux/2.6.32-696.18.7.el6.x86_64 centos/6.1 glibc/2.12
                UID:GID : 6253:100
             netrc file : None
           offline mode : False
```
```
numba                     0.42.0           py37h962f231_0
mpi                       1.0                       mpich    conda-forge
mpi4py                    3.0.1            py37hf046da1_0    conda-forge
mpich                     3.2.1             h1c2f66e_1008    conda-forge
h5py                      2.9.0           nompi_py37hf008753_1102    conda-forge
```

Thank you in advance.

**Comment by RemiLehe** [comment] 2019-06-11 13:26
Thanks for reporting this issue!
Could you also share your input script (or a modified version thereof), so that we can try to reproduce this issue?
Thanks in advance.

**Comment by Korsidar** [comment] 2019-06-11 14:10
Oh sorry, of course. 
```
# -------
# Imports
# -------
import numpy as np
from scipy.constants import c
# Import the relevant structures in FBPIC
from fbpic.main import Simulation
from fbpic.lpa_utils.laser import add_laser
from fbpic.openpmd_diag import FieldDiagnostic, ParticleDiagnostic, \
     set_periodic_checkpoint, restart_from_checkpoint

# ----------
# Parameters
# ----------

# Whether to use the GPU
use_cuda = False

# Order of the stencil for z derivatives in the Maxwell solver.
# Use -1 for infinite order, i.e. for exact dispersion relation in
# all direction (adviced for single-GPU/single-CPU simulation).
# Use a positive number (and multiple of 2) for a finite-order stencil
# (required for multi-GPU/multi-CPU with MPI). A large `n_order` leads
# to more overhead in MPI communications, but also to a more accurate
# dispersion relation for electromagnetic waves. (Typically,
# `n_order = 32` is a good trade-off.)
# See https://arxiv.org/abs/1611.05712 for more information.
n_order = 32

# The simulation box
Nz = 7032         # Number of gridpoints along z
zmax = 0.e-6    # Right end of the simulation box (meters)
zmin = -45.e-6   # Left end of the simulation box (meters)
Nr = 400          # Number of gridpoints along r
rmax = 40.e-6    # Length of the box along r (meters)
Nm = 2           # Number of modes used

# The simulation timestep
dt = (zmax-zmin)/Nz/c   # Timestep (seconds)

# The particles
p_zmin = 0.e-6  # Position of the beginning of the plasma (meters)
p_zmax = 1000.e-6 # Position of the end of the plasma (meters)
p_rmin = 0.      # Minimal radial position of the plasma (meters)
p_rmax = 40.e-6  # Maximal radial position of the plasma (meters)
n_e = 6.e18*1.e6 # Density (electrons.meters^-3)
p_nz = 2         # Number of particles per cell along z
p_nr = 2         # Number of particles per cell along r
p_nt = 4         # Number of particles per cell along theta

# The laser
a0 = 1.46          # Laser amplitude
w0 = 14.e-6       # Laser waist
ctau = 5.e-6     # Laser duration
z0 = -10.e-6      # Laser centroid
zf = 300.e-6    # Laser focal point

# The moving window
v_window = c       # Speed of the window

# The diagnostics and the checkpoints/restarts
diag_period = 31400         # Period of the diagnostics in number of timesteps
save_checkpoints = False # Whether to write checkpoint files
checkpoint_period = 100  # Period for writing the checkpoints
use_restart = False      # Whether to restart from a previous checkpoint
track_electrons = False  # Whether to track and write particle ids

# The density profile
ramp_start = 0.e-6
ramp_length = 40.e-8

def dens_func( z, r ) :
    """Returns relative density at position z and r"""
    # Allocate relative density
    n = np.ones_like(z)
    # Make linear ramp
    n = np.where( z<ramp_start+ramp_length, (z-ramp_start)/ramp_length, n )
    # Supress density before the ramp
    n = np.where( z<ramp_start, 0., n )
    return(n)

# The interaction length of the simulation (meters)
L_interact = 1000.e-6 # increase to simulate longer distance!
# Interaction time (seconds) (to calculate number of PIC iterations)
T_interact = ( L_interact + (zmax-zmin) ) / v_window
# (i.e. the time it takes for the moving window to slide across the plasma)

# ---------------------------
# Carrying out the simulation
# ---------------------------

# NB: The code below is only executed when running the script,
# (`python lwfa_script.py`), but not when importing it (`import lwfa_script`).
if __name__ == '__main__':

    # Initialize the simulation object
    sim = Simulation( Nz, zmax, Nr, rmax, Nm, dt,
        p_zmin, p_zmax, p_rmin, p_rmax, p_nz, p_nr, p_nt, n_e,
        dens_func=dens_func, zmin=zmin, boundaries='open',
        n_order=n_order, use_cuda=use_cuda )

    # Load initial fields
    # Add a laser to the fields of the simulation
    add_laser( sim, a0, w0, ctau, z0, zf=zf )

    if use_restart is False:
        # Track electrons if required (species 0 correspond to the electrons)
        if track_electrons:
            sim.ptcl[0].track( sim.comm )
    else:
        # Load the fields and particles from the latest checkpoint file
        restart_from_checkpoint( sim )

    # Configure the moving window
    sim.set_moving_window( v=v_window )

    # Add diagnostics
    sim.diags = [ FieldDiagnostic( diag_period, sim.fld, comm=sim.comm ),
                  ParticleDiagnostic( diag_period, {"electrons" : sim.ptcl[0]},
                    comm=sim.comm ) ]
    # Add checkpoints
    if save_checkpoints:
        set_periodic_checkpoint( sim, checkpoint_period )

    # Number of iterations to perform
    N_step = int(T_interact/sim.dt)

    ### Run the simulation
    sim.step( N_step )
    print('Woohoo')
```

**Comment by RemiLehe** [comment] 2019-06-12 05:18
Ok, thanks for sending the script.
Just to check: do you also see this bug at iteration 0 (e.g. when plotting "Ex" at iteration 0: is the laser missing from the plot)? 

I tried to reproduce this bug with your script (assuming that the answer to the above question is yes) using 2 CPU nodes, but was unable to do so. It might be that the bug that you observe is cluster-dependent ; i.e. that for some reason `mpi4py` from `conda-forge` does not work properly on that cluster. 

In order to check this, here are a few suggestions:
- Does your cluster provide `mpi4py` as a module? If yes, then it might be good to uninstall `mpi4py` from `conda-forge` and try running fbpic with the cluster-provided `mpi4py`. (This is for instance the approach that we use [on Summit](https://fbpic.github.io/install/install_summit.html), with `module load py-mpi4py/3.0.0-py3`)
- Otherwise: you can also try to build `mpi4py` using the default MPI compiler of your cluster (this is the approach we take on [JUWELS](https://fbpic.github.io/install/install_juwels.html) and [Comet](https://fbpic.github.io/install/install_comet.html))
- Another quick thing that you could try is checking whether this happens also with the openmpi version from `conda-forge` (as opposed to the `mpich` version):
```
conda install -c conda-forge mpi4py=*=*openmpi*
```
```

**Comment by Korsidar** [comment] 2019-06-24 06:15
Iteration 0 is ok.

I can install mpi4py as user for cluster python3 (or build it from source). 

So, I tried and got next output bug: 
![bug](https://user-images.githubusercontent.com/47625176/59995292-f01e2b00-9680-11e9-821a-7debd7b03f9c.png)

Field saving is ok, but particles save is incorrect. 

And following bad termination:
```

===================================================================================
=   BAD TERMINATION OF ONE OF YOUR APPLICATION PROCESSES
=   PID 32522 RUNNING AT sm131
=   EXIT CODE: 7
=   CLEANING UP REMAINING PROCESSES
=   YOU CAN IGNORE THE BELOW CLEANUP MESSAGES
===================================================================================
   Intel(R) MPI Library troubleshooting guide:
      https://software.intel.com/node/561764
===================================================================================
```




With anaconda openmpi I got that running processes do not see each other
FBPic start with: 
```
FBPIC (0.12.0)

Running on CPU (18 threads per process)

Initializing laser pulse on the mesh...

FBPIC (0.12.0)

Running on CPU (18 threads per process)

Initializing laser pulse on the mesh...

FBPIC (0.12.0)

Running on CPU (18 threads per process)

Initializing laser pulse on the mesh...

FBPIC (0.12.0)

Running on CPU (18 threads per process)

Initializing laser pulse on the mesh...
Done.

Done.

Done.

Done.

^MJust-In-Time compilation (up to one minute) ...^[[K
^MJust-In-Time compilation (up to one minute) ...^[[K
^MJust-In-Time compilation (up to one minute) ...^[[K
^MJust-In-Time compilation (up to one minute) ...^[[K

```
For 4 CPU per 2 nodes. It seem more as cluster bug I will try to fix it.

**Comment by RemiLehe** [comment] 2019-06-25 17:07
Thanks for letting us know about these issues.

I agree that this seems to be a problem specific to your cluster, in relationship to mpi4py. Because this bug is probably not specific to fbpic, I will close this issue for now. However, please don't hesitate to post any updates.

**Closed by RemiLehe** 2019-06-25 17:07 UTC

**Comment by RemiLehe** [comment] 2019-06-25 17:09
Note that, if you try to debug the above issue, it seems to be related to calls to the functions `Gatherv`, both for the first bug (field output):
https://github.com/fbpic/fbpic/blob/dev/fbpic/boundaries/boundary_communicator.py#L931
and for the second bug (particle output):
https://github.com/fbpic/fbpic/blob/dev/fbpic/boundaries/boundary_communicator.py#L1079

However, the bug might be difficult to track, since e.g. the first iteration does not display any problem...
